<?php

namespace App\Http\Middleware;
use Closure;
use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken as BaseVerifier;

class VerifyCsrfToken extends BaseVerifier
{
    /**
     * The URIs that should be excluded from CSRF verification.
     *
     * @var array
     */
    protected $except = [
        //
    ];
    public function handle($request, Closure $next)    //为了向数据库模拟插入数据，暂时将csrf_token关闭
    {
        //return parent::handle($request, $next); // TODO: Change the autogenerated stub

        return $next($request);
    }
}
